In [2]:
import sqlite3
import pandas as pd

In [3]:
con= sqlite3.connect("../data/movielens.db")

In [4]:
df = pd.read_sql_query("SELECT * FROM movies",con)
df.head()

,movie_id,title,release_date,video_release_date,imdb_url
0,1,Toy Story (1995),01-Jan-1995,None,http://us.imdb.com/M/title-exact?Toy%20Story%2...
1,2,GoldenEye (1995),01-Jan-1995,None,http://us.imdb.com/M/title-exact?GoldenEye%20(...
2,3,Four Rooms (1995),01-Jan-1995,None,http://us.imdb.com/M/title-exact?Four%20Rooms%...
3,4,Get Shorty (1995),01-Jan-1995,None,http://us.imdb.com/M/title-exact?Get%20Shorty%...
4,5,Copycat (1995),01-Jan-1995,None,http://us.imdb.com/M/title-exact?Copycat%20(1995)

In [5]:
schema =pd.read_sql_query("PRAGMA table_info(movies)",con)
types = schema[["name","type"]]
print("SQL column types")
display(types)

SQL column types

                 name     type
0            movie_id  INTEGER
1               title     TEXT
2        release_date     TEXT
3  video_release_date     TEXT
4            imdb_url     TEXT

In [6]:
print("Pandas column yypes")
display(df.dtypes)

Pandas column yypes

movie_id               int64
title                 object
release_date          object
video_release_date    object
imdb_url              object
dtype: object

In [7]:
compare = pd.DataFrame({
    "SQlite type": schema["type"].values,
    "Pandas type": df.dtypes.astype(str).values
}, index=df.columns)

display(compare)

                   SQlite type Pandas type
movie_id               INTEGER       int64
title                     TEXT      object
release_date              TEXT      object
video_release_date        TEXT      object
imdb_url                  TEXT      object

In [8]:
sqlite_missing = {}
for i in df.columns:
    query = f'SELECT COUNT(*) FROM movies WHERE "{i}" IS NULL'
    sqlite_missing[i] = con.execute(query).fetchone()[0]

print("Missing values Sqlite")
display(pd.Series(sqlite_missing, name = "SQlite null count"))

Missing values Sqlite

movie_id                 0
title                    0
release_date             1
video_release_date    1682
imdb_url                 3
Name: SQlite null count, dtype: int64

In [9]:
pandas_missing = df.isnull().sum()
print("Missing values in pandas")
display(pandas_missing)

Missing values in pandas

movie_id                 0
title                    0
release_date             1
video_release_date    1682
imdb_url                 3
dtype: int64

In [ ]:
#This is for Step 7, case D
users = pd.read_sql_query("SELECT * FROM users",con)
count = (~users["zip"].astype("string").str.match(r"^\d",na=False)).sum()
print("ZIP codes not starting with digit: ",count)

ZIP codes not starting with digit:  18

In [ ]:
con.close()